version: '3.4'

services:
  socialmediarabbitmq:
    image: "rabbitmq:3.9-management"
    hostname: "socialmediarabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"

  sqldataprofile:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql-container-profile
    environment:
      - SA_PASSWORD=TestProfile123
      - ACCEPT_EULA=Y
   
  profilemicroservice.api:
    image: ${DOCKER_REGISTRY-}profilemicroserviceapi
    build:
      context: .
      dockerfile: ProfileMicroService.API/Dockerfile
    environment:
      - DOCKER_ENVIROMENT=DEV_DOCKER_PROFILE
      - ASPNETCORE_ENVIROMENT=Development
    ports:
        - "5020:80"
        - "5021:443"
    depends_on:
      - "sqldataprofile"
      - "socialmediarabbitmq"

  sqldatanotification:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql-container-notification
    environment:
      - SA_PASSWORD=TestNotification123
      - ACCEPT_EULA=Y
   
  notificationmicroservice.api:
    image: ${DOCKER_REGISTRY-}notificationmicroserviceapi
    build:
      context: .
      dockerfile: NotificationMicroService.API/Dockerfile
    environment:
      - DOCKER_ENVIROMENT=DEV_DOCKER_NOTIFICATION
      - ASPNETCORE_ENVIROMENT=Development
    ports:
        - "5030:80"
        - "5031:443"
    depends_on:
      - "sqldatanotification"
      - "socialmediarabbitmq"
