version: '3.4'

services:
  socialmediarabbitmq:
    image: "rabbitmq:3.9-management"
    hostname: "socialmediarabbitmq"
    ports:
      - "5672"
      - "15672"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"

  sqldataprofile:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql-container-profile
    environment:
      - SA_PASSWORD=TestProfile123
      - ACCEPT_EULA=Y
   
  profilemicroservice.api:
    image: ${DOCKER_REGISTRY-}profilemicroserviceapi
    build:
      context: .
      dockerfile: ProfileMicroService.API/Dockerfile
    environment:
      - DOCKER_ENVIROMENT=DEV_DOCKER_PROFILE
      - ASPNETCORE_ENVIROMENT=Development
    ports:
        - "5020:80"
        - "5021:443"
    depends_on:
      - "sqldataprofile"
      - "socialmediarabbitmq"
  
  sqldatafollower:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql-container-follower
    environment:
      - SA_PASSWORD=TestFollow123
      - ACCEPT_EULA=Y
  
  followermicroservice.api:
    image: ${DOCKER_REGISTRY-}followermicroserviceapi
    build:
      context: .
      dockerfile: FollowerMicroservice.API/Dockerfile
    environment:
      - DOCKER_ENVIROMENT=DEV_DOCKER_FOLLOWER
      - ASPNETCORE_ENVIROMENT=Development
    ports:
      - "5030:80"
      - "5031:443"
    depends_on:
      - "sqldatafollower"
      - "socialmediarabbitmq"
